achopo_poster:
    resource: "@AchopoPosterBundle/Resources/config/routing.yml"
    prefix:   /

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
##fos_user_group:
##    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#
#fos_user_profile_show:
#    path: /profile
#    defaults: { _controller: FOSUserBundle:Profile:show }
# 
#fos_user_profile_edit:
#    path: /edit
#    defaults: { _controller: FOSUserBundle:Profile:edit }
##
##fos_user_profile:
##    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    
#fos_user_registration_register:
#    path: /register
#    defaults: { _controller: FOSUserBundle:Registration:register }
#    
#fos_user_registration_check_email:
#    path: /check-email
#    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
#
#fos_user_registration_confirm:
#    path: /confirm/{token}
#    defaults: { _controller: FOSUserBundle:Registration:confirm }
#    
#fos_user_registration_confirmed:
#    path: /confirmed
#    defaults: { _controller: FOSUserBundle:Registration:confirmed }
#    

 

#fos_user_registration:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#    